version: '3.8'
services:
  db:
    image: mariadb:10.2.25
    environment:
      MYSQL_USER: ${MYSQL_USER:?user undefined}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?password undefined}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?root password undefined}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?db name undefined}
    restart: always

  php:
    image: ${PHP_IMAGE:?php image undefined}:${APP_VERSION:?version not given}
    restart: always
    environment:
      APP_DEBUG: ${APP_DEBUG:-0}
      APP_ENV: ${APP_ENV:-prod}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      APP_SECRET: ${APP_SECRET:?db name undefined}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?cors undefined}
      DATABASE_URL: ${DATABASE_URL:?url undefined}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:?trusted hosts undefined}

  web-api:
    image: ${NGINX_API_IMAGE:?nginx image undefined}:${APP_VERSION:?version not given}
    depends_on:
      - php
    restart: always
    ports:
      - "8000:80"

  web-front:
    image: ${NGINX_FRONT_IMAGE:?nginx image undefined}:${APP_VERSION:?version not given}
    restart: always
    ports:
      - "8085:80"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db